version: appveyor.{build}

platform:
  - Win32
#  - x64

os:
 - Visual Studio 2013
# - Visual Studio 2015

configuration:
  - Release
#  - Debug

#environment:

init:
  # System related variables
  - cmd: set CMAKE_GENERATOR=Visual Studio 12 2013
  - cmd: if "%PLATFORM%"=="x64" set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64
  - cmd: echo CMAKE_GENERATOR=%CMAKE_GENERATOR%

  # Download/clone paths and URLs
  - cmd: set DOWNLOADS_PATH=C:\downloads
  - cmd: set REPOS_PATH=C:\repos
  - cmd: set ACE_DOWNLOAD_URL=http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.0.zip
  - cmd: set YARP_CLONE_URL=https://github.com/robotology/yarp.git

  # Print some useful informations:
  - cmd: set
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  # Create folders
  - cmd: md %DOWNLOADS_PATH%
  - cmd: md %REPOS_PATH%

  # Download and build ACE
  - cmd: echo Downloading %ACE_DOWNLOAD_URL%
  - cmd: appveyor DownloadFile "%ACE_DOWNLOAD_URL%" -FileName "%DOWNLOADS_PATH%\ace.zip"
  - cmd: 7z x -y -o"%DOWNLOADS_PATH%" "%DOWNLOADS_PATH%\ace.zip"
  - cmd: set ACE_ROOT=%DOWNLOADS_PATH%\ACE_wrappers
  - cmd: >
         echo #include "ace/config-win32.h" > %ACE_ROOT%\ace\config.h
  - cmd: msbuild "%ACE_ROOT%\ACE_wrappers_vc12.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: set PATH=%PATH%;%ACE_ROOT%\lib

  # Clone and build YARP
  - cmd: echo Cloning %YARP_CLONE_URL%
  - cmd: git clone -q --branch=master "%YARP_CLONE_URL%" "%REPOS_PATH%\yarp"
  - cmd: cmake -H"%REPOS_PATH%\yarp" -B"%REPOS_PATH%\yarp\build" -G"%CMAKE_GENERATOR%"
  - cmd: cmake --build "%REPOS_PATH%\yarp\build" --config "%CONFIGURATION%"
  - cmd: set YARP_ROOT=%REPOS_PATH%\yarp\build
  - cmd: set PATH=%PATH%;%YARP_ROOT%\bin

before_build:
  - cmd: echo Configuring project %APPVEYOR_PROJECT_NAME%
  - cmd: cmake -H"%APPVEYOR_BUILD_FOLDER%" -B"%APPVEYOR_BUILD_FOLDER%\build" -G"%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX:PATH="%APPVEYOR_BUILD_FOLDER%\install"

build:
  project: build\robotDevastation.sln
  parallel: false
  verbosity: minimal
