version: appveyor.{build}

platform:
  - Win32
#  - x64

os:
 - Visual Studio 2013
# - Visual Studio 2015

configuration:
  - Release
#  - Debug

#environment:

cache:
  - C:\ACE -> appveyor.yml
  - C:\SDL2 -> appveyor.yml

init:
  # System related variables
  - cmd: set CMAKE_GENERATOR=Visual Studio 12 2013
  - cmd: if "%PLATFORM%"=="x64" set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64
  - cmd: set SYSTEM_ARCH=%PLATFORM%
  - cmd: if "%PLATFORM%"=="Win32" set SYSTEM_ARCH=x86
  - cmd: echo CMAKE_GENERATOR=%CMAKE_GENERATOR%

  # Download/clone paths and URLs
  - cmd: set DOWNLOADS_PATH=C:\downloads
  - cmd: set REPOS_PATH=C:\repos

  - cmd: set ACE_DOWNLOAD_URL=http://download.dre.vanderbilt.edu/previous_versions/ACE-6.4.0.zip
  - cmd: set YARP_CLONE_URL=https://github.com/robotology/yarp.git
  - cmd: set SDL2_DOWNLOAD_URL=https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
  - cmd: set SDL2_IMAGE_DOWNLOAD_URL=https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.1-VC.zip
  - cmd: set SDL2_TTF_DOWNLOAD_URL=https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-VC.zip
  - cmd: set SDL2_MIXER_DOWNLOAD_URL=https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-VC.zip
  - cmd: set ZBAR_DOWNLOAD_URL=https://sourceforge.net/projects/zbar/files/latest/download

  # Print some useful informations:
  - cmd: set
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  # Create folders
  - cmd: md %DOWNLOADS_PATH%
  - cmd: md %REPOS_PATH%

  # Download and build ACE (if not in cache)
  - ps: >-
        if (Test-Path -Path "C:\ACE") {
            Write-Host "ACE found in cache"
        } else {
            Write-Host "ACE not in cache, running download and build step..."
            Write-Host "Downloading $env:ACE_DOWNLOAD_URL"
            Start-FileDownload "$env:ACE_DOWNLOAD_URL" -FileName "$env:DOWNLOADS_PATH\ace.zip"
            7z x -y -o"$env:DOWNLOADS_PATH" "$env:DOWNLOADS_PATH\ace.zip"
            Add-Content "$env:DOWNLOADS_PATH\ACE_wrappers\ace\config.h" "#include `"ace/config-win32.h`""
            msbuild "$env:DOWNLOADS_PATH\ACE_wrappers\ACE_wrappers_vc12.sln" /m /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
            Write-Host "Copying contents of $env:DOWNLOADS_PATH\ACE_wrappers to C:\ACE"
            xcopy /E /I /Y /Q "$env:DOWNLOADS_PATH\ACE_wrappers" C:\ACE
        }
  - cmd: set ACE_ROOT=C:\ACE
  - cmd: set PATH=%PATH%;%ACE_ROOT%\lib

  # Clone and build YARP
  - cmd: echo Cloning %YARP_CLONE_URL%
  - cmd: git clone -q --branch=master "%YARP_CLONE_URL%" "%REPOS_PATH%\yarp"
  - cmd: cmake -H"%REPOS_PATH%\yarp" -B"%REPOS_PATH%\yarp\build" -G"%CMAKE_GENERATOR%"
  - cmd: cmake --build "%REPOS_PATH%\yarp\build" --config "%CONFIGURATION%" -- /m /v:m
  - cmd: set YARP_ROOT=%REPOS_PATH%\yarp\build
  - cmd: set PATH=%PATH%;%YARP_ROOT%\bin

  # Download and extract SDL2 libraries (if not in cache)
  - ps: >-
        if (Test-Path -Path "C:\SDL2") {
            Write-Host "SDL2 found in cache"
        } else {
            Write-Host "SDL2 not in cache, running download and extract step..."
            Write-Host "Downloading $env:SDL2_DOWNLOAD_URL"
            Start-FileDownload "$env:SDL2_DOWNLOAD_URL" -FileName "$env:DOWNLOADS_PATH\sdl2.zip"
            Write-Host "Downloading $env:SDL2_IMAGE_DOWNLOAD_URL"
            Start-FileDownload "$env:SDL2_IMAGE_DOWNLOAD_URL" -FileName "$env:DOWNLOADS_PATH\sdl2_image.zip"
            Write-Host "Downloading $env:SDL2_TTF_DOWNLOAD_URL"
            Start-FileDownload "$env:SDL2_TTF_DOWNLOAD_URL" -FileName "$env:DOWNLOADS_PATH\sdl2_ttf.zip"
            Write-Host "Downloading $env:SDL2_MIXER_DOWNLOAD_URL"
            Start-FileDownload "$env:SDL2_MIXER_DOWNLOAD_URL" -FileName "$env:DOWNLOADS_PATH\sdl2_mixer.zip"
            7z x -y -o"$env:DOWNLOADS_PATH\SDL2_temp" "$env:DOWNLOADS_PATH\sdl2*.zip"
            Write-Host "Copying contents of $env:DOWNLOADS_PATH\SDL2_temp to C:\SDL2"
            Get-ChildItem -Directory "$env:DOWNLOADS_PATH\SDL2_temp" | ?{ $_.PSIsContainer } | ForEach-Object {
                xcopy /E /I /Y /Q $_.FullName C:\SDL2
            }
        }

  - cmd: set SDL2DIR=C:\SDL2
  - cmd: set PATH=%PATH%;%SDL2DIR%\lib\%SYSTEM_ARCH%

  # Download ZBar
  - cmd: 

before_build:
  - cmd: echo Configuring project %APPVEYOR_PROJECT_NAME%
  - cmd: cmake -H"%APPVEYOR_BUILD_FOLDER%" -B"%APPVEYOR_BUILD_FOLDER%\build" -G"%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX:PATH="%APPVEYOR_BUILD_FOLDER%\install"

build:
  project: build\robotDevastation.sln
  parallel: false
  verbosity: minimal
