version: appveyor.{build}

platform:
  - Win32
#  - x64

os:
 - Visual Studio 2013
# - Visual Studio 2015

configuration:
  - Release
#  - Debug

#environment:

init:
  - cmd: git config --global core.autocrlf true

  # System related variables
  - cmd: set CMAKE_GENERATOR=Visual Studio 12 2013
  - cmd: if "%platform%"=="x64" set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64
  - cmd: echo CMAKE_GENERATOR=%CMAKE_GENERATOR%
  - cmd: set DOWNLOADS_PATH=

  # Dependencies found in YARP and iCub packages
  - cmd: set YARP_LATEST=2.3.68

  - cmd: if "%platform%"=="Win32" set ROBOTOLOGY_ROOT=%ProgramFiles(x86)%\robotology
  - cmd: if "%platform%"=="x64" set ROBOTOLOGY_ROOT=%ProgramFiles%\robotology
  - cmd: set ROBOTOLOGY_VS=v12
  - cmd: if "%platform%"=="Win32" set ROBOTOLOGY_ARCH=x86
  - cmd: if "%platform%"=="x64" set ROBOTOLOGY_ARCH=x86_amd64

  - cmd: set ACE_REL_DIR=ACE-6.3.4_%ROBOTOLOGY_VS%_%ROBOTOLOGY_ARCH%
  - cmd: set ACE_ROOT=%ROBOTOLOGY_ROOT%\%ACE_REL_DIR%
  - cmd: set PATH=%PATH%;%ACE_ROOT%\bin

  # Other dependencies (...)

  # Installers URLs
  - cmd: set YARP_INSTALLER=https://github.com/robotology/yarp/releases/download/v%YARP_LATEST%/yarp_%YARP_LATEST%_%ROBOTOLOGY_VS%_%ROBOTOLOGY_ARCH%_1.exe

  # Print some useful informations:
  - cmd: set
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: md C:\downloads

  # Get YARP installer
  - cmd: echo Downloading %YARP_INSTALLER%
  - cmd: appveyor DownloadFile "%YARP_INSTALLER%" -FileName "C:\downloads\yarp.exe"
  - cmd: start "" /WAIT "c:\downloads\yarp.exe" /S
  - cmd: timeout 10
  - cmd: rmdir "%ROBOTOLOGY_ROOT%\yarp-%YARP_LATEST%" /S /Q
  - cmd: del "%ROBOTOLOGY_ROOT%\Uninstall_YARP.exe" /F /Q
  - cmd: del "%ROBOTOLOGY_ROOT%\uninstall_YARP.log" /F /Q

before_build:
  - cmd: cmake -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%\build -G"%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX:PATH=%APPVEYOR_BUILD_FOLDER%\install -C%APPVEYOR_BUILD_FOLDER%\scripts\admin\initial-cache.cmake

build:
  project: build\yarp.sln
  parallel: false
  verbosity: minimal
